// Generated by Echo Language Compiler
// Do not edit this file manually

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include "echo_runtime.h"

// Type definitions

// Function declarations
void main(void);

void main(void) {
    echo_print_string("Hello, Echo Language!");
    echo_print_string("Welcome to the future of systems programming!");
}

