// Generated by Echo Language Compiler
// Do not edit this file manually

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include "echo_runtime.h"

// Type definitions

// Function declarations
void main(void);

void main(void) {
    echo_print_string("=== Basic Types Demo ===");
    int32_t age = 25;
    double height = 175.5;
    bool is_student = true;
    char* name = "Alice";
    int year = 2024;
    double pi = 3.14159;
    char* greeting = "Hello";
    bool active = false;
    echo_print_string("Explicit types:");
    echo_print_string(name);
    echo_print_int(age);
    echo_print_bool(is_student);
    echo_print_string("");
    echo_print_string("Auto-inferred types:");
    echo_print_int(year);
    echo_print_string(greeting);
    echo_print_bool(active);
    int32_t sum = age + year;
    int32_t product = height * 2.0;
    echo_print_string("");
    echo_print_string("Calculations:");
    echo_print_int(sum);
}

