// Generated by Echo Language Compiler
// Do not edit this file manually

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include "echo_runtime.h"

// Type definitions

// Function declarations
void check_number(int32_t num);
void main(void);

void check_number(int32_t num) {
    if (num > 0) {
        echo_print_string("Positive number");
    }
    else {
        if (num < 0) {
            echo_print_string("Negative number");
        }
        else {
            echo_print_string("Zero");
        }
    }
}

void main(void) {
    echo_print_string("=== Control Flow Demo ===");
    int32_t temperature = 25;
    if (temperature > 20) {
        echo_print_string("It's warm outside!");
    }
    else {
        echo_print_string("It's cold outside!");
    }
    echo_print_string("");
    echo_print_string("Number checks:");
    check_number(5);
    check_number(-3);
    check_number(0);
    echo_print_string("");
    echo_print_string("Counting up:");
    for (int32_t i = 1; i <= 5; i = i + 1) {
        echo_print_int(i);
    }
    echo_print_string("");
    echo_print_string("Counting down:");
    int32_t counter = 5;
    while (counter > 0) {
        echo_print_int(counter);
        counter = counter - 1;
    }
    echo_print_string("");
    echo_print_string("Multiplication table (3x3):");
    for (int32_t row = 1; row <= 3; row = row + 1) {
        for (int32_t col = 1; col <= 3; col = col + 1) {
            int32_t product = row * col;
            echo_print_int(product);
        }
    }
    bool is_weekend = true;
    bool is_sunny = false;
    if (is_weekend && is_sunny) {
        echo_print_string("Perfect day for a picnic!");
    }
    else {
        if (is_weekend) {
            echo_print_string("Weekend, but weather could be better");
        }
        else {
            echo_print_string("Workday - stay focused!");
        }
    }
}

