// Generated by Echo Language Compiler
// Do not edit this file manually

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include "echo_runtime.h"

// Type definitions

// Function declarations
void main(void);
int max_float_integer(double a, int b);
double square_and_double_float(double x);
int square_and_double_integer(int x);
double max_float_float(double a, double b);
int max_integer_integer(int a, int b);
double add_float_float(double a, double b);
int add_integer_integer(int a, int b);
bool identity_bool(bool x);
char* identity_string(char* x);
double identity_float(double x);
int identity_integer(int x);

void main(void) {
    echo_print_string("=== Simple Generics Demo ===");
    echo_print_string("Identity function:");
    int int_id = identity_integer(42);
    double float_id = identity_float(3.14);
    char* string_id = identity_string("Hello");
    bool bool_id = identity_bool(true);
    echo_print_int(int_id);
    echo_print_string(string_id);
    echo_print_bool(bool_id);
    echo_print_string("");
    echo_print_string("Add function:");
    int sum_int = add_integer_integer(10, 20);
    double sum_float = add_float_float(1.5, 2.7);
    echo_print_int(sum_int);
    echo_print_string("");
    echo_print_string("Max function:");
    int max_int = max_integer_integer(15, 25);
    double max_float = max_float_float(3.14, 2.71);
    echo_print_int(max_int);
    echo_print_string("");
    echo_print_string("Square and double:");
    int result_int = square_and_double_integer(5);
    double result_float = square_and_double_float(2.0);
    echo_print_int(result_int);
    echo_print_string("");
    echo_print_string("Auto inference in action:");
    int x = 100;
    int y = 200;
    double combined = add_integer_integer(x, y);
    double bigger = max_integer_integer(combined, 500);
    echo_print_int(bigger);
    echo_print_string("");
    echo_print_string("Generics allow code reuse across types!");
}

int max_float_integer(double a, int b) {
    if (a > b) {
        return a;
    }
    else {
        return b;
    }
}

double square_and_double_float(double x) {
    double squared = x * x;
    double result = squared * 2;
    return result;
}

int square_and_double_integer(int x) {
    int squared = x * x;
    int result = squared * 2;
    return result;
}

double max_float_float(double a, double b) {
    if (a > b) {
        return a;
    }
    else {
        return b;
    }
}

int max_integer_integer(int a, int b) {
    if (a > b) {
        return a;
    }
    else {
        return b;
    }
}

double add_float_float(double a, double b) {
    return a + b;
}

int add_integer_integer(int a, int b) {
    return a + b;
}

bool identity_bool(bool x) {
    return x;
}

char* identity_string(char* x) {
    return x;
}

double identity_float(double x) {
    return x;
}

int identity_integer(int x) {
    return x;
}

