// Generated by Echo Language Compiler
// Do not edit this file manually

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include "echo_runtime.h"

// Type definitions

// Function declarations
void demonstrate_imports(void);
void math_operations(void);
void main(void);

void demonstrate_imports(void) {
    echo_print_string("Using full qualified names:");
    echo_print_int(42);
    echo_print_bool(true);
    echo_print_string("Using function alias:");
    echo_print_int(100);
    echo_print_string("Mixed usage works perfectly!");
}

void math_operations(void) {
    int a = 10;
    int b = 20;
    int sum = a + b;
    echo_print_string("Math results:");
    echo_print_int(sum);
    if (sum > 25) {
        echo_print_string("Sum is greater than 25");
    }
}

void main(void) {
    echo_print_string("=== Modules and Imports Demo ===");
    echo_print_string("");
    echo_print_string("Direct io::print call");
    echo_print_string("Aliased print call");
    echo_print_int(999);
    echo_print_string("");
    demonstrate_imports();
    echo_print_string("");
    math_operations();
    echo_print_string("");
    echo_print_string("Module system provides:");
    echo_print_string("- Namespace organization");
    echo_print_string("- Function aliases");
    echo_print_string("- Clean code structure");
    echo_print_string("");
    echo_print_string("All import styles work seamlessly together!");
}

