// Generated by Echo Language Compiler
// Do not edit this file manually

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include "echo_runtime.h"

// Type definitions

typedef struct {
    double x;
    double y;
} Point;

typedef struct {
    int32_t red;
    int32_t green;
    int32_t blue;
} Color;

typedef struct {
    Point top_left;
    Point bottom_right;
    Color fill_color;
} Rectangle;

// Function declarations
Point create_point(double x, double y);
Color create_color(int32_t r, int32_t g, int32_t b);
Rectangle create_rectangle(Point tl, Point br, Color color);
double calculate_area(Rectangle rect);
void print_point(Point p);
void print_color(Color c);
void print_rectangle(Rectangle rect);
void main(void);

Point create_point(double x, double y) {
    Point point = {.x = x, .y = y};
    return point;
}

Color create_color(int32_t r, int32_t g, int32_t b) {
    Color color = {.red = r, .green = g, .blue = b};
    return color;
}

Rectangle create_rectangle(Point tl, Point br, Color color) {
    Rectangle rect = {.top_left = tl, .bottom_right = br, .fill_color = color};
    return rect;
}

double calculate_area(Rectangle rect) {
    double width = rect.bottom_right.x - rect.top_left.x;
    double height = rect.bottom_right.y - rect.top_left.y;
    double area = width * height;
    return area;
}

void print_point(Point p) {
    echo_print_string("Point coordinates printed");
}

void print_color(Color c) {
    echo_print_string("Color RGB:");
    echo_print_int(c.red);
    echo_print_int(c.green);
    echo_print_int(c.blue);
}

void print_rectangle(Rectangle rect) {
    echo_print_string("Rectangle Information:");
    echo_print_string("Top-left point:");
    print_point(rect.top_left);
    echo_print_string("Bottom-right point:");
    print_point(rect.bottom_right);
    echo_print_string("Fill color:");
    print_color(rect.fill_color);
    double area = calculate_area(rect);
    echo_print_string("Area calculated");
}

void main(void) {
    echo_print_string("=== Data Structures Demo ===");
    Point p1 = create_point(0.0, 0.0);
    Point p2 = create_point(10.0, 5.0);
    Color red = create_color(255, 0, 0);
    Color blue = create_color(0, 0, 255);
    Rectangle rect1 = create_rectangle(p1, p2, red);
    Point p3 = create_point(5.0, 5.0);
    Point p4 = create_point(15.0, 10.0);
    Rectangle rect2 = create_rectangle(p3, p4, blue);
    echo_print_string("First rectangle:");
    print_rectangle(rect1);
    echo_print_string("");
    echo_print_string("Second rectangle:");
    print_rectangle(rect2);
    rect1.fill_color = blue;
    rect2.top_left.x = 0.0;
    echo_print_string("");
    echo_print_string("After modifications:");
    echo_print_string("Rectangle colors and positions updated");
    echo_print_string("");
    echo_print_string("Nested structures work well!");
}

