// Generated by Echo Language Compiler
// Do not edit this file manually

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include "echo_runtime.h"

// Type definitions

// Function declarations
void main(void);
int sort3_integer_integer_integer(int a, int b, int c);
int power_integer_integer(int base, int exp);
int fibonacci_integer(int n);
int factorial_integer(int n);
bool is_even_integer(int num);
double max3_float_float_float(double a, double b, double c);
double min3_float_float_float(double a, double b, double c);
int average_integer_integer_integer(int a, int b, int c);
int max3_integer_integer_integer(int a, int b, int c);
int min3_integer_integer_integer(int a, int b, int c);

void main(void) {
    echo_print_string("=== Generic Algorithms Demo ===");
    echo_print_string("Integer algorithms:");
    int min_int = min3_integer_integer_integer(10, 5, 15);
    int max_int = max3_integer_integer_integer(10, 5, 15);
    int avg_int = average_integer_integer_integer(10, 20, 30);
    echo_print_int(min_int);
    echo_print_int(max_int);
    echo_print_int(avg_int);
    echo_print_string("");
    echo_print_string("Float algorithms:");
    double min_float = min3_float_float_float(3.14, 2.71, 1.41);
    double max_float = max3_float_float_float(3.14, 2.71, 1.41);
    echo_print_string("Min and max calculated for floats");
    echo_print_string("");
    echo_print_string("Even/odd checks:");
    bool even_check1 = is_even_integer(4);
    bool even_check2 = is_even_integer(7);
    echo_print_bool(even_check1);
    echo_print_bool(even_check2);
    echo_print_string("");
    echo_print_string("Recursive algorithms:");
    int fact5 = factorial_integer(5);
    int fib7 = fibonacci_integer(7);
    int pow_2_3 = power_integer_integer(2, 3);
    echo_print_int(fact5);
    echo_print_int(fib7);
    echo_print_int(pow_2_3);
    echo_print_string("");
    echo_print_string("Sorting:");
    int middle = sort3_integer_integer_integer(30, 10, 20);
    echo_print_int(middle);
    echo_print_string("");
    echo_print_string("Polymorphic usage:");
    double result1 = min3_integer_integer_integer(100, 200, 150);
    double result2 = max3_float_float_float(1.1, 2.2, 1.8);
    echo_print_int(result1);
    echo_print_string("Max float calculated");
    echo_print_string("");
    echo_print_string("Generic algorithms provide code reuse!");
    echo_print_string("Same algorithm works with different types!");
}

int sort3_integer_integer_integer(int a, int b, int c) {
    int32_t min_val = min3_integer_integer_integer(a, b, c);
    int32_t max_val = max3_integer_integer_integer(a, b, c);
    int32_t middle = a + b + c - min_val - max_val;
    return middle;
}

int power_integer_integer(int base, int exp) {
    if (exp == 0) {
        return 1;
    }
    else {
        int32_t prev = power_integer_integer(base, exp - 1);
        int result = base * prev;
        return result;
    }
}

int fibonacci_integer(int n) {
    if (n <= 1) {
        return n;
    }
    else {
        int32_t fib1 = fibonacci_integer(n - 1);
        int32_t fib2 = fibonacci_integer(n - 2);
        int result = fib1 + fib2;
        return result;
    }
}

int factorial_integer(int n) {
    if (n <= 1) {
        return 1;
    }
    else {
        int32_t prev = factorial_integer(n - 1);
        int result = n * prev;
        return result;
    }
}

bool is_even_integer(int num) {
    int remainder = num % 2;
    int result = remainder == 0;
    return result;
}

double max3_float_float_float(double a, double b, double c) {
    double max_ab = a;
    if (b > max_ab) {
        max_ab = b;
    }
    int32_t result = max_ab;
    if (c > result) {
        result = c;
    }
    return result;
}

double min3_float_float_float(double a, double b, double c) {
    double min_ab = a;
    if (b < min_ab) {
        min_ab = b;
    }
    int32_t result = min_ab;
    if (c < result) {
        result = c;
    }
    return result;
}

int average_integer_integer_integer(int a, int b, int c) {
    int32_t sum = a + b + c;
    int result = sum / 3;
    return result;
}

int max3_integer_integer_integer(int a, int b, int c) {
    int max_ab = a;
    if (b > max_ab) {
        max_ab = b;
    }
    int32_t result = max_ab;
    if (c > result) {
        result = c;
    }
    return result;
}

int min3_integer_integer_integer(int a, int b, int c) {
    int min_ab = a;
    if (b < min_ab) {
        min_ab = b;
    }
    int32_t result = min_ab;
    if (c < result) {
        result = c;
    }
    return result;
}

