// Generated by Echo Language Compiler
// Do not edit this file manually

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include "echo_runtime.h"

// Type definitions

typedef struct {
    double x;
    double y;
} Vector2D;

typedef struct {
    char* name;
    int32_t health;
    int32_t score;
    Vector2D position;
} Player;

typedef struct {
    char* title;
    int32_t level;
    Player player1;
    Player player2;
} Game;

// Function declarations
Player create_player(char* name, int32_t health, Vector2D pos);
void analyze_player(Player p);
void print_game_state(Game game);
Game simulate_game_round(Game game);
void performance_test(void);
void main(void);
int32_t max_integer_i32(int a, int32_t b);
int32_t distance_integer_integer_i32_i32(int x1, int y1, int32_t x2, int32_t y2);
int clamp_i32_integer_integer(int32_t value, int min_val, int max_val);
double lerp_integer_integer_float(int start, int end, double factor);
Player add_score_i32_integer(int32_t player, int points);
Player apply_damage_i32_integer(int32_t player, int damage);
bool check_collision_i32_i32_float(int32_t p1, int32_t p2, double collision_radius);
Player move_player_i32_Vector2D_float(int32_t player, Vector2D velocity, double delta_time);
Vector2D create_vector_i32_float(int32_t x, double y);
Vector2D create_vector_float_float(double x, double y);

Player create_player(char* name, int32_t health, Vector2D pos) {
    Player p = {.name = name, .health = health, .score = 0, .position = pos};
    return p;
}

void analyze_player(Player p) {
    echo_print_string("=== Player Analysis ===");
    echo_print_string(p.name);
    echo_print_int(p.health);
    echo_print_int(p.score);
    echo_print_string("Position analyzed");
}

void print_game_state(Game game) {
    echo_print_string("=== Game State ===");
    echo_print_string(game.title);
    echo_print_int(game.level);
    echo_print_string("Player 1:");
    echo_print_string(game.player1.name);
    echo_print_int(game.player1.health);
    echo_print_int(game.player1.score);
    echo_print_string("Player 2:");
    echo_print_string(game.player2.name);
    echo_print_int(game.player2.health);
    echo_print_int(game.player2.score);
}

Game simulate_game_round(Game game) {
    echo_print_string("Starting game round simulation");
    Game updated_game = game;
    Vector2D velocity1 = create_vector_float_float(1.0, 0.5);
    Vector2D velocity2 = create_vector_i32_float(-0.5, 1.0);
    updated_game.player1 = move_player_i32_Vector2D_float(updated_game.player1, velocity1, 0.1);
    updated_game.player2 = move_player_i32_Vector2D_float(updated_game.player2, velocity2, 0.1);
    bool collision = check_collision_i32_i32_float(updated_game.player1, updated_game.player2, 4.0);
    if (collision) {
        echo_print_string("Collision detected!");
        updated_game.player1 = apply_damage_i32_integer(updated_game.player1, 10);
        updated_game.player2 = apply_damage_i32_integer(updated_game.player2, 10);
        updated_game.player1 = add_score_i32_integer(updated_game.player1, 5);
        updated_game.player2 = add_score_i32_integer(updated_game.player2, 5);
    }
    updated_game.player1 = add_score_i32_integer(updated_game.player1, 1);
    updated_game.player2 = add_score_i32_integer(updated_game.player2, 1);
    return updated_game;
}

void performance_test(void) {
    echo_print_string("=== Performance Test ===");
    int iterations = 1000;
    for (int32_t i = 0; i < iterations; i = i + 1) {
        int test1 = lerp_integer_integer_float(0, 100, 0.5);
        int32_t test2 = clamp_i32_integer_integer(i, 0, 500);
        int test3 = distance_integer_integer_i32_i32(0, 0, i, i);
        int test4 = max_integer_i32(test1, test2);
    }
    echo_print_string("Performance test completed");
    echo_print_int(iterations);
}

void main(void) {
    echo_print_string("=== Echo Language Advanced Showcase ===");
    echo_print_string("Demonstrating comprehensive language features");
    echo_print_string("");
    echo_print_string("Creating game world...");
    Vector2D pos1 = create_vector_float_float(0.0, 0.0);
    Vector2D pos2 = create_vector_float_float(10.0, 10.0);
    Player player1 = create_player("Alice", 100, pos1);
    Player player2 = create_player("Bob", 100, pos2);
    Game game = {.title = "Echo Arena", .level = 1, .player1 = player1, .player2 = player2};
    echo_print_string("Game world created");
    print_game_state(game);
    echo_print_string("");
    analyze_player(game.player1);
    analyze_player(game.player2);
    echo_print_string("");
    echo_print_string("Running game simulation...");
    Game final_game = game;
    for (int32_t round = 1; round <= 5; round = round + 1) {
        final_game = simulate_game_round(final_game);
        final_game.level = round;
    }
    echo_print_string("");
    echo_print_string("=== Final Game State ===");
    print_game_state(final_game);
    echo_print_string("");
    echo_print_string("=== Game Results ===");
    if (final_game.player1.score > final_game.player2.score) {
        echo_print_string("Winner: Player 1");
        echo_print_string(final_game.player1.name);
    }
    else {
        if (final_game.player2.score > final_game.player1.score) {
            echo_print_string("Winner: Player 2");
            echo_print_string(final_game.player2.name);
        }
        else {
            echo_print_string("Game ended in a tie!");
        }
    }
    echo_print_string("");
    performance_test();
    echo_print_string("");
    echo_print_string("=== Showcase Summary ===");
    echo_print_string("✓ Complex nested structures");
    echo_print_string("✓ Generic algorithms with multiple types");
    echo_print_string("✓ Module system with import aliases");
    echo_print_string("✓ Mathematical computations");
    echo_print_string("✓ Game simulation with collision detection");
    echo_print_string("✓ Conditional logic and state management");
    echo_print_string("✓ Performance testing loops");
    echo_print_string("✓ Comprehensive type system usage");
    echo_print_string("");
    echo_print_string("🎉 Echo Language Showcase Complete!");
    echo_print_string("Production-ready capabilities demonstrated");
    echo_print_string("Combining performance with expressiveness!");
}

int32_t max_integer_i32(int a, int32_t b) {
    if (a > b) {
        return a;
    }
    else {
        return b;
    }
}

int32_t distance_integer_integer_i32_i32(int x1, int y1, int32_t x2, int32_t y2) {
    int32_t dx = x2 - x1;
    int32_t dy = y2 - y1;
    int32_t result = dx * dx + dy * dy;
    return result;
}

int clamp_i32_integer_integer(int32_t value, int min_val, int max_val) {
    if (value < min_val) {
        return min_val;
    }
    if (value > max_val) {
        return max_val;
    }
    return value;
}

double lerp_integer_integer_float(int start, int end, double factor) {
    int diff = end - start;
    int offset = diff * factor;
    int result = start + offset;
    return result;
}

Player add_score_i32_integer(int32_t player, int points) {
    player.score = player.score + points;
    return player;
}

Player apply_damage_i32_integer(int32_t player, int damage) {
    int32_t new_health = player.health - damage;
    player.health = clamp_i32_integer_integer(new_health, 0, 100);
    return player;
}

bool check_collision_i32_i32_float(int32_t p1, int32_t p2, double collision_radius) {
    int32_t dist = distance_integer_integer_i32_i32(p1.position.x, p1.position.y, p2.position.x, p2.position.y);
    return dist < collision_radius;
}

Player move_player_i32_Vector2D_float(int32_t player, Vector2D velocity, double delta_time) {
    int32_t new_x = player.position.x + velocity.x * delta_time;
    int32_t new_y = player.position.y + velocity.y * delta_time;
    player.position.x = new_x;
    player.position.y = new_y;
    return player;
}

Vector2D create_vector_i32_float(int32_t x, double y) {
    Vector2D vec = {.x = x, .y = y};
    return vec;
}

Vector2D create_vector_float_float(double x, double y) {
    Vector2D vec = {.x = x, .y = y};
    return vec;
}

